services:
  # Go后端服务
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://game_news:game_news_password@db:27017/game_news
      - DB_NAME=game_news
    networks:
      - game_news_network

  # MongoDB数据库服务
  db:
    image: mongo:7-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: game_news
      MONGO_INITDB_ROOT_PASSWORD: game_news_password
      MONGO_INITDB_DATABASE: game_news
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - game_news_network

volumes:
  mongodb_data:

networks:
  game_news_network:
    driver: bridge