version: '3.8'

services:
  # Go后端服务
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=game_news
      - DB_PASSWORD=game_news_password
      - DB_NAME=game_news
    volumes:
      - ./game_news.db:/root/game_news.db
    networks:
      - game_news_network

  # PostgreSQL数据库服务
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: game_news
      POSTGRES_USER: game_news
      POSTGRES_PASSWORD: game_news_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - game_news_network

  # Adminer数据库管理工具
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - game_news_network

volumes:
  postgres_data:

networks:
  game_news_network:
    driver: bridge